### PR TITLE
Don't accept: Twisted compat initial cut

### PR DESCRIPTION
**Pull request by dpnova**
Initial version of twisted client, as per: https://github.com/cablehead/python-consul/issues/7
    
* Currently only some of the unit tests are implemented.
* Thus not all functionality is tested.
* Test running and quirks are documented in the test file.
* Tests aren't added to the tox config yet.
* Error handling is rough for the http client.
    
I'm mostly checking in to make sure this is an approach you're happy with.

### CODE REVIEW

**Comment by dpnova** [comment]
Coverage as the tests stand at the moment:
    
    consul/twisted       53      6    89%   29, 57-61

29 is the conversion of params to a query string and 57-61 is the error handling.

**Comment by cablehead** [comment]
Sorry for the delay in looking at these, just been snowed under. Hoping to work on this this weekend.

**Comment by cablehead** [comment]
Sorry again for taking so long to look at this.

This is looking great. Do you think there's anyway to be able to run the tests via py.test, and more importantly, make use of the fixture in tests/conftest.py to spin up a temporary instance of consul for the tests to run against? It'd be nice to be able to run the twisted tests on travis ci, along with the rest of the tests.

**Comment by cablehead** [comment]
Oops, sorry, just reading your first set of notes on this pull request more closely. You explicitly mention that tox hasn't been updated :)

- It's not too important to test off of the base functionality in your tests. really just enough to exercise all the http methods, + params, data args, and then that responses and exception handling are being massaged to the common expected more. Looking at the tests you have, it looks like GET, PUT, DELETE are getting exercised, plus params and data .. so I think maybe just add a few tests that trigger some 404, and 500 cases?

- Your approach looks spot on. But yeah, the error case looks like it needs fleshing out. 

- Would it be possible to add a example to the docs, of how usage looks with Twisted? You can delete the section in the docs that says that a Twisted client is still needed too!

**Comment by abn** [comment]
@dpnova can we close this in favor of #90 ? We have been using that patch in prod for a while and has been working as expected.

**Comment by abn** [comment]
Closing this one as #90 and #117 supercedes it.

**Pull request closed without merging**
