### PR TITLE
Consul 1 0 0

### PR DESCRIPTION
**Pull request by matusvalo**
This PR adds support of Consul v 1.0.0. This PR fixes the following issues and PRs: #179, #178, #174, #175, #176

### CODE REVIEW

**Comment by nh2** [comment]
I'm using this PR to make python-consul work with Consul 1.0.6 and it's working well so far.

**Comment by inventionlabsSydney** [comment]
@abn @cablehead could you please merge this? I'm currently having issues as a result. 👍 

Thanks!
Karl.

**Comment by cablehead** [comment]
Thanks for this. And sorry for the delay in getting it merged. The PR is perfect.

**Comment by inventionlabsSydney** [comment]
Pew pew! Thanks!

**Pull request merged**
