### PR TITLE
Fix parmas usage

### PR DESCRIPTION
**Pull request by sayuan**
A minor fixed which is the missing changes from #190

### CODE REVIEW

**Comment by matusvalo** [comment]
Thank you @sayuan. I missed this when reviewing #190. I think that we need to bugfix release 1.1.1 with this fix. @cablehead  what do you think?

**Comment by df11** [comment]
I confirm, a bugfix release 1.1.1 would be very useful.
Thanks for the fix

**Comment by shamil** [comment]
Yep, seems like `1.1.0` is not useful when loading tokens. Can we have a new release?

**Comment by Techcadia** [comment]
This is broken in CentOS 7 running Python 2.7.5 rev 76
https://centos.pkgs.org/7/centos-x86_64/python-2.7.5-76.el7.x86_64.rpm.html

as it seems to be upstreamed by someone into the rpm base package.

**Pull request merged**
