### PR TITLE
Adding ability to register checks with services

### PR DESCRIPTION
**Pull request by cruatta**
This should fix https://github.com/cablehead/python-consul/issues/36. I did a quick test and it worked fine. Thanks for taking a look!

### CODE REVIEW

**Comment by cablehead** [comment]
Thanks for this. Is it possible to add a test for it, and to update the doc string?

What happens if you call with a service id that doesn't exist? Is the service part just ignored, or is a new service created?

**Comment by cruatta** [comment]
I'll work on those. I would like some guidance in what you'd like to see in a test since this doesn't really change the behavior of /agent/check/register much. To answer your question, the behavior is the check is not registered and consul returns an error.
```
ServiceID "foo" does not exist
```
If a ServiceName is specified without a ServiceID, as you would expect Consul ignores the invalid ServiceName and registers the check without a ServiceID or ServiceName.

**Comment by cablehead** [comment]
What do you think about omitting ServiceName as an option? I can't see
that it does anything?

Maybe add a new test, test_agent_checks_service_id that:

- tries to register a check, with a service_id that doesn't exists,
asserts a sane exception is raised.. maybe NotFound? Or just
ConsulException, depending on what Consul gives you to work with.

- create the service, and then the check, assert that the check
succeeded and is linked to the service.

**Comment by cruatta** [comment]
I would keep ServiceName for two reasons: To be as completely API compatible with consul as possible and because it's a nice convenience. Say you're registering a check for service "tudb1-s7". Having a human readable service name like "Test User Database 1 - Shard 7" paired with your check definition is something that might make troubleshooting easier when you're reading the output of the status of your checks.

**Comment by cruatta** [comment]
I'm also completely unable to reproduce the failure Travis is seeing with my branch on pypy.

```
(python-consul-pypy)cruat-mb13r:python-consul cameron.ruatta$ git branch
* add-service-info-to-checks
  master
(python-consul-pypy)cruat-mb13r:python-consul cameron.ruatta$ export TOX_ENV pypy
(python-consul-pypy)cruat-mb13r:python-consul cameron.ruatta$ tox -e $TOX_ENV
GLOB sdist-make: /Users/cameron.ruatta/projects/python-consul/python-consul/setup.py
pypy inst-nodeps: /Users/cameron.ruatta/projects/python-consul/python-consul/.tox/dist/python-consul-0.3.15.zip
pypy runtests: PYTHONHASHSEED='3464884491'
pypy runtests: commands[0] | py.test --reruns=3 consul tests
================================================================ test session starts =================================================================
platform darwin -- Python 2.7.8[pypy-2.5.0-final] -- py-1.4.26 -- pytest-2.7.0
rootdir: /Users/cameron.ruatta/projects/python-consul/python-consul, inifile:
plugins: rerunfailures
collected 40 items

tests/test_base.py ...
tests/test_std.py .........................
tests/test_tornado.py ............

============================================================= 40 passed in 10.95 seconds =============================================================
______________________________________________________________________ summary _______________________________________________________________________
  pypy: commands succeeded
  congratulations :)
```

Any help from you in debugging this would be much appreciated while I work on those tests :)

**Comment by cablehead** [comment]
There's an intermittent timing related failure in the tests. You should be right to ignore that. I'll confirm when I merge. 

Ah - so if you don't include the service name, it doesn't get associated with the check, even though the previously created service has a name?

**Comment by cruatta** [comment]
It looks like when you're registering a check, whatever you set ServiceName to automatically gets overwritten by consul when the check is registered:

https://github.com/hashicorp/consul/blob/master/command/agent/agent.go#L712

This means we could actually get rid of ServiceName since it's essentially useless to provide it.

**Comment by cablehead** [comment]
Interesting. Yeah, I'd vote for leaving it out. Especially since
documentation for this feature is so hard to come by, that people won't
have a reason to expect to be able to pass it.

**Comment by cablehead** [comment]
Just checking if you'd like to add a test for this, maybe: test_agent_checks_service_id ?

I can as well. The docstring just needs updating as well.

**Comment by cruatta** [comment]
Sorry, work has been eating up all my time. Hoping to have some time to finish up the tests and docstrings this weekend.

**Comment by cruatta** [comment]
Docstring updated and tests created for asyncio. Since this feature isn't really specific to any of the frameworks I just picked aio. Do you want tests for the others as well?

**Comment by cablehead** [comment]
Actually, and this is totally nitpicking, it it possible to move the test over to test_std? Keeps things simple.

It's only really important to test the http wrappers to they async clients.

**Comment by cruatta** [comment]
Okay moved the tests! Sorry again about the delay.

**Comment by cablehead** [comment]
Thanks for this! No worries at all. I can more than relate :)

**Comment by cablehead** [comment]
Tagged and pushed to pypi as v0.3.18

**Pull request merged**
