### PR TITLE
Add asyncio support

### PR DESCRIPTION
**Pull request by jettify**
Hi,
I have added adapter for asyncio support using aiohttp as http client. All tests was ported from tornado, and couple of them still failing. Looks like I need to fix time sleep constants. 

Please review.

### CODE REVIEW

**Comment by jettify** [comment]
Ok, tests for py34 not falling on travisci, but pyflakes is complaining on invalid syntax on other test envs... I need figure out how to disable aio.py for py27 pyflakes check.

**Comment by cablehead** [comment]
Yeah, due to timing issues tests fail intermittently at the moment. I need to rework to the tests to not be timing dependent. Thanks for this!

**Comment by cablehead** [comment]
Oh, actually, is it possible to update the docs to describe usage using aio client? Similar to: https://github.com/cablehead/python-consul/blob/master/docs/index.rst#tornado

**Comment by jettify** [comment]
Sure, I'll make separate PR with docs.

**Comment by cablehead** [comment]
Awesome, appreciate it.

I've added an explicit flake8 to the tox py34 job which doesn't ignore *aio.py, so we can still have a lint in place for that code:

https://github.com/cablehead/python-consul/commit/c4b22d896ef3ef85727646ddcc265feb604ef992

Gawd, the whole python3 situation is a mess.

I also added an extras_requires. Once this is up on pypi, it should be possible to pull in aiohttp with:

```
pip install python-consul[asyncio]
```

https://github.com/cablehead/python-consul/commit/b956984fd8d864bba661169839feb491e73db42e

**Comment by jettify** [comment]
you are right, thanks for fix.

**Pull request merged**
