### PR TITLE
Build refactor

### PR DESCRIPTION
**Pull request by abn**

### CODE REVIEW

**Comment by cablehead** [comment]
This is super cool. Want to do the honors and merge!?

**Comment by abn** [comment]
@cablehead done! :) Might need to add `python-consul-admin` pypi user to the authorised users to upload builds.

**Comment by abn** [comment]
@cablehead the first scan results are available at https://sonarcloud.io/dashboard?id=com.github%3Acablehead%3Apython-consul

**Comment by cablehead** [comment]
Added! I've added you as well (abn).

**Pull request merged**
