### PR TITLE
Added keys_only and separator options to kv.get

### PR DESCRIPTION
**Pull request by Heuriskein**
Used keys_only rather than keys for the parameter because I thought it was clearer, but I can understand if you want to change that to just keys to match the 0.4.1 interface.

Also, this is my first pull request ever so let me know if I should be doing something different.

### CODE REVIEW

**Comment by cablehead** [comment]
Thanks for this!

Yeah, I think we should match the underlying Consul interface. Let's make it just keys. Is it possible to add these two flags to the docstring and to add a test for them? You can just test them in test_std .. no need to test in the async libs. I just pulled in another merge requests which added the dc param, which is conflicting with this one. I don't suppose you could pull that in to resolve conflicts?

**Comment by Heuriskein** [comment]
Sure thing.

**Comment by Heuriskein** [comment]
Hey Andy, I made the changes to the interface locally, and I'm trying to
run tox and several tests seem to fail (and not consistent tests either). I
don't want to push broken code to your repo, but I'm not really able to
test things in a way I'm comfortable with.

Is the intention that I should be able to clone the repo into a vm, install
python-tox, and just run "tox" or is there more that I need to do?

**Comment by cablehead** [comment]
Hi Ryan.. Yeah, sorry, unfortunately there's a timing related intermittent fail in the tests. I need to rework the tests to not be timing dependent. It sounds like what you have is right. You should be right to push up what you have.



—

**Pull request closed without merging**
