### PR TITLE
added dc support for kv

### PR DESCRIPTION
**Pull request by angad**

### CODE REVIEW

**Comment by cablehead** [comment]
I'm just worried about providing the option to set a default dc on the client. 

If we go that route, all calls which support the dc arg should pick up this default e.g. https://github.com/angad/python-consul/blob/master/consul/base.py#L497 

But not all Consul endpoints work with a dc arg .. which kinda makes setting it for the entire client a little weird. The ACL endpoints don't, for example. It might be unintuitive that by setting dc on the client, a lot of the calls will work with that dc, but not all of the calls.

**Comment by angad** [comment]
Since it is given that 
"In any Consul cluster, only a single datacenter is authoritative for ACLs, so all requests are automatically routed to that datacenter regardless of the agent that the request is made to."

Can't we safely omit the dc arg when making calls to the ACL endpoints?

Though, I feel that the ACL endpoints should work when supplied with the authoritative DC (and not completely fail with _rpc error: ACL not found_)- though that change would have to be within consul's ACL API.

**Comment by cablehead** [comment]
Ah, good point. So I guess all endpoints *do* work with a dc argument, exception ACL, which explicitly doesn't. In which case, we should update calls which do take a dc argument to pick up the default set on the client. Would you be able to this, and I'll merge in?

**Comment by angad** [comment]
Added. 

Asked on the consul mailing list to support dc param for ACL endpoints - but doesnt impact this pull request.

**Comment by cablehead** [comment]
Awesome, thank you!

**Comment by cablehead** [comment]
Tagged and pushed to Pypi as version 0.3.7

https://pypi.python.org/pypi/python-consul/0.3.7

**Comment by angad** [comment]
great!
The ACL DC param was opened as an issue in consul 
https://github.com/hashicorp/consul/issues/698

Since token and dc can be params for any http request, should we have them as kwargs with a basic check in each function?

**Comment by cablehead** [comment]
If I'm reading Armon's comment right, ACL shouldn't accept the dc arg - so
I think what we have for the ACL method signatures is right. I.e., you
shouldn't be able to pass dc to the ACL endpoints.

I want to keep the method signature's explicit vs using kwargs - that way
autodocs generate meaningful documentation, and it's clear at a glance
which options you have available to you for an endpoint. Consul.io has
great documentation - but sometimes I find because its so verbose it's
tough to see a glance all available options. I'm starting to find the
functions signatures in the Python lib to be a good reference! :)

**Pull request merged**
