### PR TITLE
Add twisted adapter using treq

### PR DESCRIPTION
**Pull request by joshainglis**
Adds a twisted adapter.
Used the tornado adapter as a template.

Requires [treq](https://github.com/twisted/treq) which should pull in all of the other requirements.

### CODE REVIEW

**Comment by cablehead** [comment]
Nice!

Is the additional code to support SSL needed? It looks like pyopenssl is an optional dependency of treq, so guessing treq already has SSL support?

Additionally:

1/ is it possible to run flake8 over `consul/twisted.py`?
2/ is it possible to add enough tests to have confidence that base.py is being wrapped OK. 1 test of a long polling nature, and then a maybe pick some commands to hit each of the HTTP methods should be enough.
3/ If this is merged, and I get you set up with commit access, could you be available to field any related issues / pull requests that come up?

**Comment by abn** [comment]
@joshainglis i have fixed some issues [https://github.com/abn/python-consul/commit/00e2bb80a624fc3e72d33600018d9239df2aff2a] and did some refactor [https://github.com/abn/python-consul/commit/7801b84f7c9b869a214b99f23ab2dd52748f9d5d]. The rebased branch is at https://github.com/abn/python-consul/tree/pr/90

Can you update your branch?

**Comment by abn** [comment]
@joshainglis also fixed up the flake8 issues

**Comment by abn** [comment]
Added initial tests at https://github.com/abn/python-consul/commit/602a49e9cd7b2b2be4220d15dc4dcfc148fe9793

**Comment by dpnova** [comment]
What's the extra ssl stuff for? (I have some interest in the state of this in twisted)

**Comment by joshainglis** [comment]
@abn Thanks! Rebased with your changes

**Comment by abn** [comment]
@joshainglis some bug fixes were added just now to my branch.

**Comment by 2mf** [comment]
What is the status about this pull request?
I would prefer having a twisted adapter added in python-consul rather than having to put this patch into my code.

**Comment by abn** [comment]
@2mf we have been using this for a while, and I am waiting on a few cleanups from @joshainglis relating to the SSLContext implementations before merging it in; otherwise it is ready fwiw.

Note there are a few python3 issues which i have fixed on my branch. Hopefully should be in master next week.

**Comment by abn** [comment]
@joshainglis I am closing this in favor of #117. I have squashed the commits and cleaned up a few things as per the above discussions and dropped the custom SSL Context handling in favor of a simpler more flexible solution.

**Comment by joshainglis** [comment]
@abn: LGTM

**Pull request closed without merging**
