### PR TITLE
add finalizer to the __del__ magic method for python3.4.1

### PR DESCRIPTION
**Pull request by jettify**
I've added ``__del__`` magic method in order to close http connections on garbage collection, like aiohttp/aiopg/aiomysql does. This PR address #47 issue too.

### CODE REVIEW

**Comment by jettify** [comment]
To be honest, I have too add test...

**Comment by cablehead** [comment]
Roger. Night!

**Comment by jettify** [comment]
I've added test but it is not working properly, and I am not sure why... Somehow ``py.test`` does not want to catch ``ResourceWarning``, however I see this warning at my console output:
```
tests/test_aio.py /home/nick/sources/python/python-consul/consul/aio.py:48: ResourceWarning: Unclosed connector in aio.Consul.HTTPClient
```
I am not familiar with ``py.test`` much, have I missed something?

**Comment by cablehead** [comment]
Might just need a gc.collect to ensure c is collected, for the __del__ to be called. I'll merge and patch.

**Comment by cablehead** [comment]
Looks great. Thanks again for jumping in on this.

**Comment by jettify** [comment]
Thanks for the fix) I completely forget about such ``del`` behaviour

**Pull request merged**
