### PR TITLE
Add nodemeta to catalog and health end points

### PR DESCRIPTION
**Pull request by ibrahimmenem**
very simple PR to add support to node metadata introduced in consul 0.7.3.

### CODE REVIEW

**Comment by ibrahimmenem** [comment]
hey @cablehead @abn, it seems that latest version of pytest_twisted breaks your CI, I pinned it to the previous version `1.5` so the tests are passing. I'd really appreciate your comment on this PR.

**Comment by ihpu** [comment]
I am also missing this feature in the library. Would be great to add this to the next version

**Comment by apakulov-stripe** [comment]
Hi @cablehead and @abn! 
Do you have plans release this change soon?

**Comment by matusvalo** [comment]
Thank you for your PR.

According to documentation of consul it is possible to specify multiple times (see [1]). In proposed implementation it is possible to post only single key:value against server. Is it possible to rewrite params to be in form of sequence of two-element tuples? This is also accepted by `urlib.parse.urlencode` [2] which process params variable in `base.HTTPClient.uri`.

Moreover is it possible to use dictionary instead of string 'key:value'? This is proposed API:

```python
consul.catalog.nodes(node_meta={'a':'b', 'c':'d'})
```

In this form PR will be perfect. Please let me know if it is feasible for you.

[1] https://www.consul.io/api/catalog.html#node-meta
[2] https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode

**Comment by ibrahimmenem** [comment]
hi @matusvalo, thanks for answering! this sounds like a little bit bigger change but I think I can do it during the weekend.

**Comment by ibrahimmenem** [comment]
@matusvalo I think the PR is ready, please tell me if it looks good to you. 
thanks

**Comment by matusvalo** [comment]
PR seems OK. I am merging it. Thank you @ibrahimmenem .

**Comment by hreidar** [comment]
@ibrahimmenem Any interest in adding this node_meta functionality to /catalog/register API also? so we can add metadata when registering external nodes to Consul.

[https://www.consul.io/api/catalog.html#nodemeta](url)

**Comment by hreidar** [comment]
@ibrahimmenem my coding skills are not that good so I'll leave it to you ;-) Thank you.

**Pull request merged**
