### PR TITLE
Closes #24. Adding support for the /health/state/* endpoint

### LINKED ISSUE #24: Unable to pull all service health
With Consul.Health.service() I can pull the current health of a specified service. I'd like to be able to pull the current health of *all* services. This is how I do it with the consul CLI:

consul watch -type=checks cat

Like the current Health.service(), I need to use an index so that I can continually pull changes to the health checks. It looks like this is not possible with Consul.Health.service(), and I don't see how to do it with any of the other classes.

### PR DESCRIPTION
**Pull request by pete0emerson**
I think this does the trick. I copied your tests for the service endpoint and fixed them up a bit. It's not exhaustive (I only check `any` and `passing`, for example), but I hope  it's a good enough first step.

### CODE REVIEW

**Comment by pete0emerson** [comment]
Okay, formatting fixed, but CI is still failing. Not sure why at the moment.

**Comment by cablehead** [comment]
There's an intermittent timing fail in the tests .. might just be that.

**Comment by pete0emerson** [comment]
I guess that makes sense when you're relying on sleep() to ensure data consistency. I suppose you could widen the sleeps to have a higher likelihood of success, at the expense of slower tests ...

**Comment by cablehead** [comment]
It's on my todo list to make them more deterministic .. It's be good to
rework them so they don't rely on sleeps at all.

**Comment by pete0emerson** [comment]
Ah, I forgot to add the assert for the name parameter. I'll add that in.

**Comment by cablehead** [comment]
Thanks Pete! I've tagged and pushed to pypi as v0.3.11

**Pull request merged**
