### PR TITLE
add health/node/<node> endpoint

### PR DESCRIPTION
**Pull request by davidbirdsong**
covers half of #53

### CODE REVIEW

**Comment by cablehead** [comment]
Just checking, what happens if you make the call for a node that doesn't exist?

**Comment by davidbirdsong** [comment]
Looks ok:
```python
>>> c.health.node('foo')
('4327740', [])
>>> c.health.node('bar')
('4327740', [])
>>> c.health.node(None)
('4327740', [])
```

**Comment by cablehead** [comment]
sweet!

**Comment by cablehead** [comment]
Pushed up to Pypi as v0.4.1

**Pull request merged**
