### PR TITLE
Health: add support for token

### PR DESCRIPTION
**Pull request by morpheu**
When using Consul configured with strict acl access, all health paths require token

### CODE REVIEW

**Comment by benagricola** [comment]
Suspect your test failure in the last build is due to a timing issue with starting / stopping consul on Travis - I managed to work around it in PR #93 (all tests were passing locally) by bumping the sleeps while the test framework waits for consul to start up and gain leadership.

**Comment by abn** [comment]
Tests are passing at https://travis-ci.org/cablehead/python-consul/builds/111186900

@morpheu can you remove the fix in conftest and squash d10ce4eea2b32170b82f11959fa5ff0180b055e3 and cee54bf7a2f0ebb95fb104ebcc809d2051b19569? That will be handled with #100

**Comment by morpheu** [comment]
Done!

**Comment by abn** [comment]
Merged with f5fc28a..6219f6f

Thanks @morpheu

**Pull request closed without merging**
